# Generated by Django 5.1.1 on 2025-05-11 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='precio',
            field=models.IntegerField(),
        ),
    ]
