# Generated by Django 5.1.1 on 2025-05-14 19:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0001_initial'),
    ]

    operations = [
    ]
