name: Rapi

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    services:
      mysql:
        image: mysql:8.0
        env:
          MYSQL_ROOT_PASSWORD: Emajose12.
          MYSQL_DATABASE: django
        ports:
          - 3306:3306
        options: >-
          --health-cmd="mysqladmin ping --silent"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=3
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Wait for MySQL
        run: |
          until mysqladmin ping -h"127.0.0.1" -uroot -pEmajose12. --silent; do
            sleep 2
          done
      - name: Run migrations
        run: |
          cd Rapi
          python manage.py migrate
      - name: Run tests
        run: |
          cd Rapi
          python manage.py test
