name: Rapi

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Clean pip cache
        run: pip cache purge
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          
      - name: Configurar conexión a MySQL en Railway
        run: |
            echo "DATABASE_URL=mysql://root:NITYcFflUTIpPornmfmltltgYCtSiSEM@switchyard.proxy.rlwy.net:50121/railway" >> $GITHUB_ENV
      
      - name: Validar conexión con Railway MySQL
        run: |
          mysql -h switchyard.proxy.rlwy.net -u root -pNITYcFflUTIpPornmfmltltgYCtSiSEM --port 50121 -e "SHOW DATABASES;"

      - name: Run migrations
        run: |
          cd Rapi
          python manage.py migrate


      - name: Run tests
        run: |
          cd Rapi
          python manage.py test --keepdb
